import googlemaps
gmaps = googlemaps.Client(key='AIzaSyDF0Ax8m7_MSENM9_HlALzW6XLHYJnM2Co')

COMMODITY_CATEGORIES = (("FOOD GRAINS/ CEREALS","FOOD GRAINS/ CEREALS"),("OILSEEDS","OILSEEDS"),("FRUITS","FRUITS"),
                        ("VEGETABLES","VEGETABLES"),("SPICES","SPICES"),("MISC","MISC"))

BID_STATUS = (("Initiated", "Initiated"),("Completed", "Completed"),("Cancelled", "Cancelled"),
              ("Partially Completed", "Partially Completed"), ("Other", "Other"))

GENDER_CHOICES = (("Male", "Male"),("Female", "Female"),("Unknown", "Unknown"),("Other", "Other"))

KYC_ID_CHOICES = (("ADHAR CARD", "ADHAR CARD"),("PAN CARD", "PAN CARD"),("VOTER CARD", "VOTER CARD"),("OTHERS", "OTHERS"))

STATUS_CHOICES = (("PENDING", "PENDING"),("INITIATED", "INITIATED"),("COMPLETED", "COMPLETED"),("OTHERS", "OTHERS"))


STATE_CHOICES = (("Andhra Pradesh","Andhra Pradesh"),("Arunachal Pradesh ","Arunachal Pradesh "),
                 ("Assam","Assam"),("Bihar","Bihar"),("Chhattisgarh","Chhattisgarh"),("Goa","Goa"),
                 ("Gujarat","Gujarat"),("Haryana","Haryana"),("Himachal Pradesh","Himachal Pradesh"),
                 ("Jammu and Kashmir ","Jammu and Kashmir "),("Jharkhand","Jharkhand"),("Karnataka","Karnataka"),
                 ("Kerala","Kerala"),("Madhya Pradesh","Madhya Pradesh"),("Maharashtra","Maharashtra"),
                 ("Manipur","Manipur"),("Meghalaya","Meghalaya"),("Mizoram","Mizoram"),("Nagaland","Nagaland"),
                 ("Odisha","Odisha"),("Punjab","Punjab"),("Rajasthan","Rajasthan"),("Sikkim","Sikkim"),
                 ("Tamil Nadu","Tamil Nadu"),("Telangana","Telangana"),("Tripura","Tripura"),
                 ("Uttar Pradesh","Uttar Pradesh"),("Uttarakhand","Uttarakhand"),("West Bengal","West Bengal"),
                 ("Andaman and Nicobar Islands","Andaman and Nicobar Islands"),("Chandigarh","Chandigarh"),
                 ("Dadra and Nagar Haveli","Dadra and Nagar Haveli"),("Daman and Diu","Daman and Diu"),
                 ("Lakshadweep","Lakshadweep"),
                 ("National Capital Territory of Delhi","National Capital Territory of Delhi"),
                 ("Puducherry","Puducherry"))
Andhra_Pradesh = (('Anantapur', 'Anantapur'), ('Chittoor', 'Chittoor'), ('East Godavari', 'East Godavari'), ('Guntur', 'Guntur'), ('YSR Kadapa', 'YSR Kadapa'), ('Krishna', 'Krishna'), ('Kurnool', 'Kurnool'), ('Prakasam', 'Prakasam'), ('Sri Potti Sriramulu Nellore', 'Sri Potti Sriramulu Nellore'), ('Srikakulam', 'Srikakulam'), ('Visakhapatnam', 'Visakhapatnam'), ('Vizianagaram', 'Vizianagaram'), ('West Godavari', 'West Godavari'))
Arunachal_Pradesh = (('Anjaw', 'Anjaw'), ('Changlang', 'Changlang'), ('East Kameng', 'East Kameng'), ('East Siang', 'East Siang'), ('Kamle', 'Kamle'), ('Kra Daadi', 'Kra Daadi'), ('Kurung Kumey', 'Kurung Kumey'), ('Lepa Rada', 'Lepa Rada'), ('Lohit', 'Lohit'), ('Longding', 'Longding'), ('Lower Dibang Valley', 'Lower Dibang Valley'), ('Lower Siang', 'Lower Siang'), ('Lower Subansiri', 'Lower Subansiri'), ('Namsai', 'Namsai'), ('Pakke-Kessang', 'Pakke-Kessang'), ('Papum Pare', 'Papum Pare'), ('Shi Yomi', 'Shi Yomi'), ('Siang', 'Siang'), ('Tawang', 'Tawang'), ('Tirap', 'Tirap'), ('Upper Dibang Valley', 'Upper Dibang Valley'), ('Upper Siang', 'Upper Siang'), ('Upper Subansiri', 'Upper Subansiri'), ('West Kameng', 'West Kameng'), ('West Siang', 'West Siang'))
Assam = (('Baksa', 'Baksa'), ('Barpeta', 'Barpeta'), ('Bishwanath', 'Bishwanath'), ('Bongaigaon', 'Bongaigaon'), ('Cachar', 'Cachar'), ('Charaideo', 'Charaideo'), ('Chirang', 'Chirang'), ('Darrang', 'Darrang'), ('Dhemaji', 'Dhemaji'), ('Dhubri', 'Dhubri'), ('Dibrugarh', 'Dibrugarh'), ('Dima Hasao', 'Dima Hasao'), ('Goalpara', 'Goalpara'), ('Golaghat', 'Golaghat'), ('Hailakandi', 'Hailakandi'), ('Hojai', 'Hojai'), ('Jorhat', 'Jorhat'), ('Kamrup', 'Kamrup'), ('Kamrup Metropolitan', 'Kamrup Metropolitan'), ('Karbi Anglong', 'Karbi Anglong'), ('Karimganj', 'Karimganj'), ('Kokrajhar', 'Kokrajhar'), ('Lakhimpur', 'Lakhimpur'), ('Majuli', 'Majuli'), ('Morigaon', 'Morigaon'), ('Nagaon', 'Nagaon'), ('Nalbari', 'Nalbari'), ('Sivasagar', 'Sivasagar'), ('South Salmara', 'South Salmara'), ('Sonitpur', 'Sonitpur'), ('Tinsukia', 'Tinsukia'), ('Udalguri', 'Udalguri'), ('West Karbi Anglong', 'West Karbi Anglong'))
Bihar = (('Araria', 'Araria'), ('Arwal', 'Arwal'), ('Aurangabad', 'Aurangabad'), ('Banka', 'Banka'), ('Begusarai', 'Begusarai'), ('Bhagalpur', 'Bhagalpur'), ('Bhojpur', 'Bhojpur'), ('Buxar', 'Buxar'), ('Darbhanga', 'Darbhanga'), ('East Champaran', 'East Champaran'), ('Gaya', 'Gaya'), ('Gopalganj', 'Gopalganj'), ('Jamui', 'Jamui'), ('Jehanabad', 'Jehanabad'), ('Kaimur', 'Kaimur'), ('Katihar', 'Katihar'), ('Khagaria', 'Khagaria'), ('Kishanganj', 'Kishanganj'), ('Lakhisarai', 'Lakhisarai'), ('Madhepura', 'Madhepura'), ('Madhubani', 'Madhubani'), ('Munger', 'Munger'), ('Muzaffarpur', 'Muzaffarpur'), ('Nalanda', 'Nalanda'), ('Nawada', 'Nawada'), ('Patna', 'Patna'), ('Purnia', 'Purnia'), ('Rohtas', 'Rohtas'), ('Saharsa', 'Saharsa'), ('Samastipur', 'Samastipur'), ('Saran', 'Saran'), ('Sheikhpura', 'Sheikhpura'), ('Sheohar', 'Sheohar'), ('Sitamarhi', 'Sitamarhi'), ('Siwan', 'Siwan'), ('Supaul', 'Supaul'), ('Vaishali', 'Vaishali'), ('West Champaran', 'West Champaran'))
Chhattisgarh = (('Balod', 'Balod'), ('Baloda Bazar', 'Baloda Bazar'), ('Balrampur', 'Balrampur'), ('Bastar', 'Bastar'), ('Bemetara', 'Bemetara'), ('Bijapur', 'Bijapur'), ('Bilaspur', 'Bilaspur'), ('Dantewada', 'Dantewada'), ('Dhamtari', 'Dhamtari'), ('Durg', 'Durg'), ('Gariaband', 'Gariaband'), ('Gaurela-Pendra-Marwahi', 'Gaurela-Pendra-Marwahi'), ('Janjgir-Champa', 'Janjgir-Champa'), ('Jashpur', 'Jashpur'), ('Kabirdham', 'Kabirdham'), ('Kanker', 'Kanker'), ('Kondagaon', 'Kondagaon'), ('Korba', 'Korba'), ('Koriya', 'Koriya'), ('Mahasamund', 'Mahasamund'), ('Mungeli', 'Mungeli'), ('Narayanpur', 'Narayanpur'), ('Raigarh', 'Raigarh'), ('Raipur', 'Raipur'), ('Rajnandgaon', 'Rajnandgaon'), ('Sukma', 'Sukma'), ('Surajpur', 'Surajpur'), ('Surguja', 'Surguja'))
Goa = (('North Goa', 'North Goa'), ('South Goa', 'South Goa'))
Gujarat = (('Ahmedabad', 'Ahmedabad'), ('Amreli', 'Amreli'), ('Anand', 'Anand'), ('Aravalli', 'Aravalli'), ('Banaskantha', 'Banaskantha'), ('Bharuch', 'Bharuch'), ('Bhavnagar', 'Bhavnagar'), ('Botad', 'Botad'), ('Chhota Udepur', 'Chhota Udepur'), ('Dahod', 'Dahod'), ('Dang', 'Dang'), ('Devbhoomi Dwarka', 'Devbhoomi Dwarka'), ('Gandhinagar', 'Gandhinagar'), ('Gir Somnath', 'Gir Somnath'), ('Jamnagar', 'Jamnagar'), ('Junagadh', 'Junagadh'), ('Kheda', 'Kheda'), ('Kutch', 'Kutch'), ('Mahisagar', 'Mahisagar'), ('Mehsana', 'Mehsana'), ('Morbi', 'Morbi'), ('Narmada', 'Narmada'), ('Navsari', 'Navsari'), ('Panchmahal', 'Panchmahal'), ('Patan', 'Patan'), ('Porbandar', 'Porbandar'), ('Rajkot', 'Rajkot'), ('Sabarkantha', 'Sabarkantha'), ('Surat', 'Surat'), ('Surendranagar', 'Surendranagar'), ('Tapi', 'Tapi'), ('Vadodara', 'Vadodara'), ('Valsad', 'Valsad'))
Haryana = (('Ambala', 'Ambala'), ('Bhiwani', 'Bhiwani'), ('Charkhi Dadri', 'Charkhi Dadri'), ('Faridabad', 'Faridabad'), ('Fatehabad', 'Fatehabad'), ('Gurgaon', 'Gurgaon'), ('Hissar', 'Hissar'), ('Jhajjar', 'Jhajjar'), ('Jind', 'Jind'), ('Kaithal', 'Kaithal'), ('Karnal', 'Karnal'), ('Kurukshetra', 'Kurukshetra'), ('Mahendragarh', 'Mahendragarh'), ('Nuh', 'Nuh'), ('Palwal', 'Palwal'), ('Panchkula', 'Panchkula'), ('Panipat', 'Panipat'), ('Rewari', 'Rewari'), ('Rohtak', 'Rohtak'), ('Sirsa', 'Sirsa'), ('Sonipat', 'Sonipat'), ('Yamuna Nagar', 'Yamuna Nagar'))
Himachal_Pradesh = (('Bilaspur', 'Bilaspur'), ('Chamba', 'Chamba'), ('Hamirpur', 'Hamirpur'), ('Kangra', 'Kangra'), ('Kinnaur', 'Kinnaur'), ('Kullu', 'Kullu'), ('Lahaul and Spiti', 'Lahaul and Spiti'), ('Mandi', 'Mandi'), ('Shimla', 'Shimla'), ('Sirmaur', 'Sirmaur'), ('Solan', 'Solan'), ('Una', 'Una'))
Jharkhand = (('Bokaro', 'Bokaro'), ('Chatra', 'Chatra'), ('Deoghar', 'Deoghar'), ('Dhanbad', 'Dhanbad'), ('Dumka', 'Dumka'), ('East Singhbhum', 'East Singhbhum'), ('Garhwa', 'Garhwa'), ('Giridih', 'Giridih'), ('Godda', 'Godda'), ('Gumla', 'Gumla'), ('Hazaribag', 'Hazaribag'), ('Jamtara', 'Jamtara'), ('Khunti', 'Khunti'), ('Koderma', 'Koderma'), ('Latehar', 'Latehar'), ('Lohardaga', 'Lohardaga'), ('Pakur', 'Pakur'), ('Palamu', 'Palamu'), ('Ramgarh', 'Ramgarh'), ('Ranchi', 'Ranchi'), ('Sahibganj', 'Sahibganj'), ('Seraikela Kharsawan', 'Seraikela Kharsawan'), ('Simdega', 'Simdega'), ('West Singhbhum', 'West Singhbhum'))
Karnataka = (('Bagalkot', 'Bagalkot'), ('Ballari', 'Ballari'), ('Belgaum', 'Belgaum'), ('Bangalore Rural', 'Bangalore Rural'), ('Bangalore Urban', 'Bangalore Urban'), ('Bidar', 'Bidar'), ('Chamarajnagar', 'Chamarajnagar'), ('Chikkaballapur', 'Chikkaballapur'), ('Chikkamagaluru', 'Chikkamagaluru'), ('Chitradurga', 'Chitradurga'), ('Dakshina Kannada', 'Dakshina Kannada'), ('Davanagere', 'Davanagere'), ('Dharwad', 'Dharwad'), ('Gadag', 'Gadag'), ('Gulbarga', 'Gulbarga'), ('Hassan', 'Hassan'), ('Haveri', 'Haveri'), ('Kodagu', 'Kodagu'), ('Kolar', 'Kolar'), ('Koppal', 'Koppal'), ('Mandya', 'Mandya'), ('Mysuru', 'Mysuru'), ('Raichur', 'Raichur'), ('Ramanagara', 'Ramanagara'), ('Shimoga', 'Shimoga'), ('Tumakuru', 'Tumakuru'), ('Udupi', 'Udupi'), ('Uttara Kannada', 'Uttara Kannada'), ('Vijayapura', 'Vijayapura'), ('Yadgir', 'Yadgir'))
Kerala = (('Alappuzha', 'Alappuzha'), ('Ernakulam', 'Ernakulam'), ('Idukki', 'Idukki'), ('Kannur', 'Kannur'), ('Kasaragod', 'Kasaragod'), ('Kollam', 'Kollam'), ('Kottayam', 'Kottayam'), ('Kozhikode', 'Kozhikode'), ('Malappuram', 'Malappuram'), ('Palakkad', 'Palakkad'), ('Pathanamthitta', 'Pathanamthitta'), ('Thrissur', 'Thrissur'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Wayanad', 'Wayanad'))
Madhya_Pradesh = (('Agar Malwa', 'Agar Malwa'), ('Alirajpur', 'Alirajpur'), ('Anuppur', 'Anuppur'), ('Ashok Nagar', 'Ashok Nagar'), ('Balaghat', 'Balaghat'), ('Barwani', 'Barwani'), ('Betul', 'Betul'), ('Bhind', 'Bhind'), ('Bhopal', 'Bhopal'), ('Burhanpur', 'Burhanpur'), ('Chachaura-Binaganj', 'Chachaura-Binaganj'), ('Chhatarpur', 'Chhatarpur'), ('Chhindwara', 'Chhindwara'), ('Damoh', 'Damoh'), ('Datia', 'Datia'), ('Dewas', 'Dewas'), ('Dhar', 'Dhar'), ('Dindori', 'Dindori'), ('Guna', 'Guna'), ('Gwalior', 'Gwalior'), ('Harda', 'Harda'), ('Hoshangabad', 'Hoshangabad'), ('Indore', 'Indore'), ('Jabalpur', 'Jabalpur'), ('Jhabua', 'Jhabua'), ('Katni', 'Katni'), ('Khandwa (East Nimar)', 'Khandwa (East Nimar)'), ('Khargone (West Nimar)', 'Khargone (West Nimar)'), ('Maihar', 'Maihar'), ('Mandla', 'Mandla'), ('Mandsaur', 'Mandsaur'), ('Morena', 'Morena'), ('Narsinghpur', 'Narsinghpur'), ('Nagda', 'Nagda'), ('Neemuch', 'Neemuch'), ('Niwari', 'Niwari'), ('Panna', 'Panna'), ('Raisen', 'Raisen'), ('Rajgarh', 'Rajgarh'), ('Ratlam', 'Ratlam'), ('Rewa', 'Rewa'), ('Sagar', 'Sagar'), ('Satna', 'Satna'), ('Sehore', 'Sehore'), ('Seoni', 'Seoni'), ('Shahdol', 'Shahdol'), ('Shajapur', 'Shajapur'), ('Sheopur', 'Sheopur'), ('Shivpuri', 'Shivpuri'), ('Sidhi', 'Sidhi'), ('Singrauli', 'Singrauli'), ('Tikamgarh', 'Tikamgarh'), ('Ujjain', 'Ujjain'), ('Umaria', 'Umaria'), ('Vidisha', 'Vidisha'))
Maharashtra = (('Ahmednagar', 'Ahmednagar'), ('Akola', 'Akola'), ('Amravati', 'Amravati'), ('Aurangabad', 'Aurangabad'), ('Beed', 'Beed'), ('Bhandara', 'Bhandara'), ('Buldhana', 'Buldhana'), ('Chandrapur', 'Chandrapur'), ('Dhule', 'Dhule'), ('Gadchiroli', 'Gadchiroli'), ('Gondia', 'Gondia'), ('Hingoli', 'Hingoli'), ('Jalgaon', 'Jalgaon'), ('Jalna', 'Jalna'), ('Kolhapur', 'Kolhapur'), ('Latur', 'Latur'), ('Mumbai City', 'Mumbai City'), ('Mumbai suburban', 'Mumbai suburban'), ('Nanded', 'Nanded'), ('Nandurbar', 'Nandurbar'), ('Nagpur', 'Nagpur'), ('Nashik', 'Nashik'), ('Osmanabad', 'Osmanabad'), ('Palghar', 'Palghar'), ('Parbhani', 'Parbhani'), ('Pune', 'Pune'), ('Raigad', 'Raigad'), ('Ratnagiri', 'Ratnagiri'), ('Sangli', 'Sangli'), ('Satara', 'Satara'), ('Sindhudurg', 'Sindhudurg'), ('Solapur', 'Solapur'), ('Thane', 'Thane'), ('Wardha', 'Wardha'), ('Washim', 'Washim'), ('Yavatmal', 'Yavatmal'))
Manipur = (('Bishnupur', 'Bishnupur'), ('Chandel', 'Chandel'), ('Churachandpur', 'Churachandpur'), ('Imphal East', 'Imphal East'), ('Imphal West', 'Imphal West'), ('Jiribam', 'Jiribam'), ('Kakching', 'Kakching'), ('Kamjong', 'Kamjong'), ('Kangpokpi', 'Kangpokpi'), ('Noney', 'Noney'), ('Pherzawl', 'Pherzawl'), ('Senapati', 'Senapati'), ('Tamenglong', 'Tamenglong'), ('Tengnoupal', 'Tengnoupal'), ('Thoubal', 'Thoubal'), ('Ukhrul', 'Ukhrul'))
Meghalaya = (('East Garo Hills', 'East Garo Hills'), ('East Khasi Hills', 'East Khasi Hills'), ('East Jaintia Hills', 'East Jaintia Hills'), ('North Garo Hills', 'North Garo Hills'), ('Ri Bhoi', 'Ri Bhoi'), ('South Garo Hills', 'South Garo Hills'), ('South West Garo Hills', 'South West Garo Hills'), ('South West Khasi Hills', 'South West Khasi Hills'), ('West Jaintia Hills', 'West Jaintia Hills'), ('West Garo Hills', 'West Garo Hills'), ('West Khasi Hills', 'West Khasi Hills'))
Mizoram = (('Aizawl', 'Aizawl'), ('Champhai', 'Champhai'), ('Hnahthial', 'Hnahthial'), ('Khawzawl', 'Khawzawl'), ('Kolasib', 'Kolasib'), ('Lawngtlai', 'Lawngtlai'), ('Lunglei', 'Lunglei'), ('Mamit', 'Mamit'), ('Saiha', 'Saiha'), ('Saitual', 'Saitual'), ('Serchhip', 'Serchhip'))
Nagaland = (('Dimapur', 'Dimapur'), ('Kiphire', 'Kiphire'), ('Kohima', 'Kohima'), ('Longleng', 'Longleng'), ('Mokokchung', 'Mokokchung'), ('Mon', 'Mon'), ('Noklak', 'Noklak'), ('Peren', 'Peren'), ('Phek', 'Phek'), ('Tuensang', 'Tuensang'), ('Wokha', 'Wokha'), ('Zunheboto', 'Zunheboto'))
Odisha = (('Angul', 'Angul'), ('Boudh (Bauda)', 'Boudh (Bauda)'), ('Bhadrak', 'Bhadrak'), ('Balangir', 'Balangir'), ('Bargarh (Baragarh)', 'Bargarh (Baragarh)'), ('Balasore', 'Balasore'), ('Cuttack', 'Cuttack'), ('Debagarh (Deogarh)', 'Debagarh (Deogarh)'), ('Dhenkanal', 'Dhenkanal'), ('Ganjam', 'Ganjam'), ('Gajapati', 'Gajapati'), ('Jharsuguda', 'Jharsuguda'), ('Jajpur', 'Jajpur'), ('Jagatsinghpur', 'Jagatsinghpur'), ('Khordha', 'Khordha'), ('Kendujhar (Keonjhar)', 'Kendujhar (Keonjhar)'), ('Kalahandi', 'Kalahandi'), ('Kandhamal', 'Kandhamal'), ('Koraput', 'Koraput'), ('Kendrapara', 'Kendrapara'), ('Malkangiri', 'Malkangiri'), ('Mayurbhanj', 'Mayurbhanj'), ('Nabarangpur', 'Nabarangpur'), ('Nuapada', 'Nuapada'), ('Nayagarh', 'Nayagarh'), ('Puri', 'Puri'), ('Rayagada', 'Rayagada'), ('Sambalpur', 'Sambalpur'), ('Subarnapur (Sonepur)', 'Subarnapur (Sonepur)'), ('Sundargarh', 'Sundargarh'))
Punjab = (('Amritsar', 'Amritsar'), ('Barnala', 'Barnala'), ('Bathinda', 'Bathinda'), ('Firozpur', 'Firozpur'), ('Faridkot', 'Faridkot'), ('Fatehgarh Sahib', 'Fatehgarh Sahib'), ('Fazilka[14]', 'Fazilka[14]'), ('Gurdaspur', 'Gurdaspur'), ('Hoshiarpur', 'Hoshiarpur'), ('Jalandhar', 'Jalandhar'), ('Kapurthala', 'Kapurthala'), ('Ludhiana', 'Ludhiana'), ('Mansa', 'Mansa'), ('Moga', 'Moga'), ('Sri Muktsar Sahib', 'Sri Muktsar Sahib'), ('Pathankot', 'Pathankot'), ('Patiala', 'Patiala'), ('Rupnagar', 'Rupnagar'), ('Sahibzada Ajit Singh Nagar', 'Sahibzada Ajit Singh Nagar'), ('Sangrur', 'Sangrur'), ('Shahid Bhagat Singh Nagar', 'Shahid Bhagat Singh Nagar'), ('Tarn Taran', 'Tarn Taran'))
Rajasthan = (('Ajmer', 'Ajmer'), ('Alwar', 'Alwar'), ('Bikaner', 'Bikaner'), ('Barmer', 'Barmer'), ('Banswara', 'Banswara'), ('Bharatpur', 'Bharatpur'), ('Baran', 'Baran'), ('Bundi', 'Bundi'), ('Bhilwara', 'Bhilwara'), ('Churu', 'Churu'), ('Chittorgarh', 'Chittorgarh'), ('Dausa', 'Dausa'), ('Dholpur', 'Dholpur'), ('Dungarpur', 'Dungarpur'), ('Ganganagar', 'Ganganagar'), ('Hanumangarh', 'Hanumangarh'), ('Jhunjhunu', 'Jhunjhunu'), ('Jalore', 'Jalore'), ('Jodhpur', 'Jodhpur'), ('Jaipur', 'Jaipur'), ('Jaisalmer', 'Jaisalmer'), ('Jhalawar', 'Jhalawar'), ('Karauli', 'Karauli'), ('Kota', 'Kota'), ('Nagaur', 'Nagaur'), ('Pali', 'Pali'), ('Pratapgarh', 'Pratapgarh'), ('Rajsamand', 'Rajsamand'), ('Sikar', 'Sikar'), ('Sawai Madhopur', 'Sawai Madhopur'), ('Sirohi', 'Sirohi'), ('Tonk', 'Tonk'), ('Udaipur', 'Udaipur'))
Sikkim = (('East Sikkim', 'East Sikkim'), ('North Sikkim', 'North Sikkim'), ('South Sikkim', 'South Sikkim'), ('West Sikkim', 'West Sikkim'))
Tamil_Nadu = (('Ariyalur', 'Ariyalur'), ('Chengalpattu', 'Chengalpattu'), ('Chennai', 'Chennai'), ('Coimbatore', 'Coimbatore'), ('Cuddalore', 'Cuddalore'), ('Dharmapuri', 'Dharmapuri'), ('Dindigul', 'Dindigul'), ('Erode', 'Erode'), ('Kallakurichi', 'Kallakurichi'), ('Kanchipuram', 'Kanchipuram'), ('Kanyakumari', 'Kanyakumari'), ('Karur', 'Karur'), ('Krishnagiri', 'Krishnagiri'), ('Madurai', 'Madurai'), ('Mayiladuthurai', 'Mayiladuthurai'), ('Nagapattinam', 'Nagapattinam'), ('Nilgiris', 'Nilgiris'), ('Namakkal', 'Namakkal'), ('Perambalur', 'Perambalur'), ('Pudukkottai', 'Pudukkottai'), ('Ramanathapuram', 'Ramanathapuram'), ('Ranipet', 'Ranipet'), ('Salem', 'Salem'), ('Sivaganga', 'Sivaganga'), ('Tenkasi', 'Tenkasi'), ('Tirupur', 'Tirupur'), ('Tiruchirappalli', 'Tiruchirappalli'), ('Theni', 'Theni'), ('Tirunelveli', 'Tirunelveli'), ('Thanjavur', 'Thanjavur'), ('Thoothukudi', 'Thoothukudi'), ('Tirupattur', 'Tirupattur'), ('Tiruvallur', 'Tiruvallur'), ('Tiruvarur', 'Tiruvarur'), ('Tiruvannamalai', 'Tiruvannamalai'), ('Vellore', 'Vellore'), ('Viluppuram', 'Viluppuram'), ('Virudhunagar', 'Virudhunagar'))
Telangana = (('Adilabad', 'Adilabad'), ('Komaram Bheem', 'Komaram Bheem'), ('Bhadradri Kothagudem', 'Bhadradri Kothagudem'), ('Hyderabad', 'Hyderabad'), ('Jagtial', 'Jagtial'), ('Jangaon', 'Jangaon'), ('Jayashankar Bhupalpally', 'Jayashankar Bhupalpally'), ('Jogulamba Gadwal', 'Jogulamba Gadwal'), ('Kamareddy', 'Kamareddy'), ('Karimnagar', 'Karimnagar'), ('Khammam', 'Khammam'), ('Mahabubabad', 'Mahabubabad'), ('Mahbubnagar', 'Mahbubnagar'), ('Mancherial', 'Mancherial'), ('Medak', 'Medak'), ('Medchal-Malkajgiri', 'Medchal-Malkajgiri'), ('Mulugu', 'Mulugu'), ('Nalgonda', 'Nalgonda'), ('Narayanpet', 'Narayanpet'), ('Nagarkurnool', 'Nagarkurnool'), ('Nirmal', 'Nirmal'), ('Nizamabad', 'Nizamabad'), ('Peddapalli', 'Peddapalli'), ('Rajanna Sircilla', 'Rajanna Sircilla'), ('Ranga Reddy', 'Ranga Reddy'), ('Sangareddy', 'Sangareddy'), ('Siddipet', 'Siddipet'), ('Suryapet', 'Suryapet'), ('Vikarabad', 'Vikarabad'), ('Wanaparthy', 'Wanaparthy'), ('Warangal Urban', 'Warangal Urban'), ('Warangal Rural', 'Warangal Rural'), ('Yadadri Bhuvanagiri', 'Yadadri Bhuvanagiri'))
Tripura = (('Dhalai', 'Dhalai'), ('Gomati', 'Gomati'), ('Khowai[15]', 'Khowai[15]'), ('North Tripura', 'North Tripura'), ('Sepahijala[16]', 'Sepahijala[16]'), ('South Tripura', 'South Tripura'), ('Unokoti[17]', 'Unokoti[17]'), ('West Tripura', 'West Tripura'))
Uttar_Pradesh = (('Agra', 'Agra'), ('Aligarh', 'Aligarh'), ('Prayagraj', 'Prayagraj'), ('Ambedkar Nagar', 'Ambedkar Nagar'), ('Amethi', 'Amethi'), ('Amroha', 'Amroha'), ('Auraiya', 'Auraiya'), ('Azamgarh', 'Azamgarh'), ('Bagpat', 'Bagpat'), ('Bahraich', 'Bahraich'), ('Ballia', 'Ballia'), ('Balrampur', 'Balrampur'), ('Banda', 'Banda'), ('Barabanki', 'Barabanki'), ('Bareilly', 'Bareilly'), ('Basti', 'Basti'), ('Bhadohi', 'Bhadohi'), ('Bijnor', 'Bijnor'), ('Budaun', 'Budaun'), ('Bulandshahr', 'Bulandshahr'), ('Chandauli', 'Chandauli'), ('Chitrakoot', 'Chitrakoot'), ('Deoria', 'Deoria'), ('Etah', 'Etah'), ('Etawah', 'Etawah'), ('Ayodhya', 'Ayodhya'), ('Farrukhabad', 'Farrukhabad'), ('Fatehpur', 'Fatehpur'), ('Firozabad', 'Firozabad'), ('Gautam Buddh Nagar', 'Gautam Buddh Nagar'), ('Ghaziabad', 'Ghaziabad'), ('Ghazipur', 'Ghazipur'), ('Gonda', 'Gonda'), ('Gorakhpur', 'Gorakhpur'), ('Hamirpur', 'Hamirpur'), ('Hapur', 'Hapur'), ('Hardoi', 'Hardoi'), ('Hathras', 'Hathras'), ('Jalaun', 'Jalaun'), ('Jaunpur', 'Jaunpur'), ('Jhansi', 'Jhansi'), ('Kannauj', 'Kannauj'), ('Kanpur Dehat', 'Kanpur Dehat'), ('Kanpur Nagar', 'Kanpur Nagar'), ('Kasganj', 'Kasganj'), ('Kaushambi', 'Kaushambi'), ('Kushinagar', 'Kushinagar'), ('Lakhimpur Kheri', 'Lakhimpur Kheri'), ('Lalitpur', 'Lalitpur'), ('Lucknow', 'Lucknow'), ('Maharajganj', 'Maharajganj'), ('Mahoba', 'Mahoba'), ('Mainpuri', 'Mainpuri'), ('Mathura', 'Mathura'), ('Mau', 'Mau'), ('Meerut', 'Meerut'), ('Mirzapur', 'Mirzapur'), ('Moradabad', 'Moradabad'), ('Muzaffarnagar', 'Muzaffarnagar'), ('Pilibhit', 'Pilibhit'), ('Pratapgarh', 'Pratapgarh'), ('Raebareli', 'Raebareli'), ('Rampur', 'Rampur'), ('Saharanpur', 'Saharanpur'), ('Sambhal', 'Sambhal'), ('Sant Kabir Nagar', 'Sant Kabir Nagar'), ('Shahjahanpur', 'Shahjahanpur'), ('Shamli[18]', 'Shamli[18]'), ('Shravasti', 'Shravasti'), ('Siddharthnagar', 'Siddharthnagar'), ('Sitapur', 'Sitapur'), ('Sonbhadra', 'Sonbhadra'), ('Sultanpur', 'Sultanpur'), ('Unnao', 'Unnao'), ('Varanasi', 'Varanasi'))
Uttarakhand = (('Almora', 'Almora'), ('Bageshwar', 'Bageshwar'), ('Chamoli', 'Chamoli'), ('Champawat', 'Champawat'), ('Dehradun', 'Dehradun'), ('Haridwar', 'Haridwar'), ('Nainital', 'Nainital'), ('Pauri Garhwal', 'Pauri Garhwal'), ('Pithoragarh', 'Pithoragarh'), ('Rudraprayag', 'Rudraprayag'), ('Tehri Garhwal', 'Tehri Garhwal'), ('Udham Singh Nagar', 'Udham Singh Nagar'), ('Uttarkashi', 'Uttarkashi'))
West_Bengal = (('Alipurduar', 'Alipurduar'), ('Bankura', 'Bankura'), ('Paschim Bardhaman', 'Paschim Bardhaman'), ('Purba Bardhaman', 'Purba Bardhaman'), ('Birbhum', 'Birbhum'), ('Cooch Behar', 'Cooch Behar'), ('Dakshin Dinajpur', 'Dakshin Dinajpur'), ('Darjeeling', 'Darjeeling'), ('Hooghly', 'Hooghly'), ('Howrah', 'Howrah'), ('Jalpaiguri', 'Jalpaiguri'), ('Jhargram', 'Jhargram'), ('Kalimpong', 'Kalimpong'), ('Kolkata', 'Kolkata'), ('Maldah', 'Maldah'), ('Murshidabad', 'Murshidabad'), ('Nadia', 'Nadia'), ('North 24 Parganas', 'North 24 Parganas'), ('Paschim Medinipur', 'Paschim Medinipur'), ('Purba Medinipur', 'Purba Medinipur'), ('Purulia', 'Purulia'), ('South 24 Parganas', 'South 24 Parganas'), ('Uttar Dinajpur', 'Uttar Dinajpur'))

